steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/bash
  args: 
    - '-c'
    - |
        gcloud compute instances describe ${_DEPLOY_INSTANCE_NAME} --zone ${_DEPLOY_INSTANCE_ZONE} > gce-vm-status.txt
        echo gce-vm-status.txt