steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/cobalt-compound-279315/nodejs-docker-webapp:$COMMIT_SHA', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/cobalt-compound-279315/nodejs-docker-webapp:$COMMIT_SHA']
